### ISSUE TITLE
'tokio-runtime-worker' panicked at 'SinkImpl::poll_flush called after error.'

### ISSUE THREAD

**Issue by ltfschoen** [DataHighway-DHX/DataHighway-Parachain#52]
I got the following error when syncing my Tanganika node with the relay and parachain, i'd synced ~11846441 out of 15934569, with 11846144 finalized blocks on relay chain and 1044591 out of 1104968 blocks with 0 finalized on parachain:
```
root@localhost:~# journalctl -u datahighway.service -f
Dec 26 07:50:46 localhost start.sh[29519]:       std::sys::unix::thread::Thread::new::thread_start
Dec 26 07:50:46 localhost start.sh[29519]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/sys/unix/thread.rs:108:17
Dec 26 07:50:46 localhost start.sh[29519]:   39: <unknown>
Dec 26 07:50:46 localhost start.sh[29519]:   40: <unknown>
Dec 26 07:50:46 localhost start.sh[29519]: Thread 'tokio-runtime-worker' panicked at 'SinkImpl::poll_ready called after error.', /home/sudip/.cargo/registry/src/github.com-1ecc6299db9ec823/quicksink-0.1.2/src/lib.rs:158
```
i was using: 
https://github.com/DataHighway-DHX/DataHighway-Parachain/releases/download/v3.7.1/datahighway-collator https://github.com/DataHighway-DHX/DataHighway-Parachain/releases/download/v3.7.1/kusama.json
https://raw.githubusercontent.com/DataHighway-DHX/DataHighway-Parachain/v3.6.0/res/kusama/kusama-parachain-raw.json

It seems related to this https://github.com/paritytech/substrate/issues/12522

when i restarted the node it continued syncing relay chain blocks, but stopped syncing parachain blocks and showed the following error:
```
Error importing block 0x9a12c8dc3df1aab3f72ed5e0abfd7b15e9f9b50f4a15643f12058e3a5bf47897: consensus error: Import failed: Backend error: Can't canonicalize missing block number #1044592 when importing 0x9a12c8dc3df1aab3f72ed5e0abfd7b15e9f9b50f4a15643f12058e3a5bf47897 (#1048688)
```

**Comment by ltfschoen** [comment]
i got the same error trying to sync relay chain block 12462435
